<a href="https://colab.research.google.com/github/fadhilindrasta/Tugas2-Preproccesing-Data-mining/blob/main/Tugas2_Preproccesing_Fadhil_Indrasta_A11_2020_12558.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import fungsi yang akan digunakan :

In [20]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Memasukan dataset :



In [38]:
dataset = pd.read_csv('cuaca.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

Pengecekan attribut :

In [39]:
print(x)

[[23. 30. 25. 93.  3.]
 [24. 34. 28. 86.  6.]
 [24. 29. 25. 94.  1.]
 [22. 33. 27. 86.  7.]
 [23. 32. 26. 88.  3.]
 [23. 33. 27. 87.  5.]
 [24. 32. 26. 88.  5.]
 [23. 30. 26. nan  1.]
 [23. 32. 26. 82.  6.]
 [23. 31. 26. 89.  5.]
 [23. 32. 27. 82.  5.]
 [24. 31. 26. 88.  3.]]


pengecekan label :




In [40]:
print(y)

['Lebat' 'Lebat' 'Lebat' 'S.Lebat' 'S.Lebat' 'Lebat' 'Lebat' 'Lebat'
 'Lebat' 'Lebat' 'Lebat' 'Lebat']


mengisi value yang kosong (nan) dengan rata-rata.

 :

In [41]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [42]:
print(x)

[[23. 30. 25. 93.  3.]
 [24. 34. 28. 86.  6.]
 [24. 29. 25. 94.  1.]
 [22. 33. 27. 86.  7.]
 [23. 32. 26. 88.  3.]
 [23. 33. 27. 87.  5.]
 [24. 32. 26. 88.  5.]
 [23. 30. 26. nan  1.]
 [23. 32. 26. 82.  6.]
 [23. 31. 26. 89.  5.]
 [23. 32. 27. 82.  5.]
 [24. 31. 26. 88.  3.]]


mengencoding data kategori(atribut) menjadi numerik & matriks :

In [43]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [44]:
print(x)

[[ 0.  1.  0. 30. 25. 93.  3.]
 [ 0.  0.  1. 34. 28. 86.  6.]
 [ 0.  0.  1. 29. 25. 94.  1.]
 [ 1.  0.  0. 33. 27. 86.  7.]
 [ 0.  1.  0. 32. 26. 88.  3.]
 [ 0.  1.  0. 33. 27. 87.  5.]
 [ 0.  0.  1. 32. 26. 88.  5.]
 [ 0.  1.  0. 30. 26. nan  1.]
 [ 0.  1.  0. 32. 26. 82.  6.]
 [ 0.  1.  0. 31. 26. 89.  5.]
 [ 0.  1.  0. 32. 27. 82.  5.]
 [ 0.  0.  1. 31. 26. 88.  3.]]


mengencoding data label menjadi numerik & matriks :

In [45]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [46]:
print(y)

[0 0 0 1 1 0 0 0 0 0 0 0]


Membagi dataset ke dalam training set dan test set :

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [48]:
print(x_train)

[[ 0.  1.  0. 32. 27. 82.  5.]
 [ 0.  0.  1. 34. 28. 86.  6.]
 [ 0.  0.  1. 32. 26. 88.  5.]
 [ 0.  1.  0. 30. 25. 93.  3.]
 [ 0.  1.  0. 30. 26. nan  1.]
 [ 0.  0.  1. 31. 26. 88.  3.]
 [ 0.  1.  0. 31. 26. 89.  5.]
 [ 0.  1.  0. 32. 26. 82.  6.]
 [ 0.  1.  0. 33. 27. 87.  5.]]


In [49]:
print(x_test)

[[ 0.  0.  1. 29. 25. 94.  1.]
 [ 1.  0.  0. 33. 27. 86.  7.]
 [ 0.  1.  0. 32. 26. 88.  3.]]


In [50]:
print(y_train)

[0 0 0 0 0 0 0 0 0]


In [51]:
print(y_test)

[0 1 1]


Feature Scaling pada kasus ini menggunakan standardscalling :

In [52]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] =sc.transform(x_test[:, 3:])

In [53]:
print(x_train)

[[ 0.          1.          0.          0.26726124  0.81649658 -1.43077123
   0.42640143]
 [ 0.          0.          1.          1.87082869  2.04124145 -0.25680509
   1.06600358]
 [ 0.          0.          1.          0.26726124 -0.40824829  0.33017798
   0.42640143]
 [ 0.          1.          0.         -1.33630621 -1.63299316  1.79763565
  -0.85280287]
 [ 0.          1.          0.         -1.33630621 -0.40824829         nan
  -2.13200716]
 [ 0.          0.          1.         -0.53452248 -0.40824829  0.33017798
  -0.85280287]
 [ 0.          1.          0.         -0.53452248 -0.40824829  0.62366951
   0.42640143]
 [ 0.          1.          0.          0.26726124 -0.40824829 -1.43077123
   1.06600358]
 [ 0.          1.          0.          1.06904497  0.81649658  0.03668644
   0.42640143]]


In [54]:
print(x_test)

[[ 0.          0.          1.         -2.13808994 -1.63299316  2.09112719
  -2.13200716]
 [ 1.          0.          0.          1.06904497  0.81649658 -0.25680509
   1.70560573]
 [ 0.          1.          0.          0.26726124 -0.40824829  0.33017798
  -0.85280287]]
